### ISSUE TITLE
Additional check: isComponent must be false on some OOC statements

### ISSUE THREAD

**Issue by kd-ods** [openownership/lib-cove-bods#77]
If an OOC statement contains one or more interests where `beneficialOwnershipOrControl` is true then `isComponent` at the statement level must be false.

See: https://standard.openownership.org/en/master/schema/guidance/repr-beneficial-ownership.html (replace 'master' with '0.3.0' once released)

**Comment by StephenAbbott** [comment]
@odscjames Test should be applied to 0.2, 0.3 and 0.3+

**Comment by kd-ods** [comment]
@StephenAbbott - I'm not sure we really can apply this test to 0.2 fairly, since we only set out these requirements clearly with the 0.3 release. What do you think?

**Comment by StephenAbbott** [comment]
@kd-ods Hmmm. I was thinking that since we wrote the extra documentation for 0.3 in light of observations that 0.2 publishers were not using `isComponent` as intended, then it would be a useful test for 0.2 as well. But happy to defer to your better judgment on this front...

**Comment by kd-ods** [comment]
@StephenAbbott - If there were a way of doing the test and then providing a warning for 0.2 data, but a validation error for 0.3 data that would be ideal. @odscjames - is that possible?

**Comment by kd-ods** [comment]
Talking to @odscjames, there is no difference between a warning and a validation error. Given that, I think we should apply this as a validation check for both 0.2 and 0.3 data.

**Comment by odscjames** [comment]
The library will output checks with no difference between them and others.

However:
* the Cove UI can choose to display different types of checks differently, and could do so based on 0.2 or 0.3+
* we could attach some kind of "priority" or "importance" flag to the checks coming out of the library. Doing so would help other people using the library to filter the results by giving them a hint on what we think - but ultimately other people writing UI's would still be free to display the results as they want.

This also comes up in another issue; maybe thinking about this can move to another issue so that things are considered together. For now I'll just write the check into the library.

**Comment by Blueskies00** [comment]
@kd-ods I need to talk through the isComponent rules with you again please, before I'm comfortable with what I'm testing! Having said that, on the first test, the review tool is doing as instructed.

**Comment by kd-ods** [comment]
@odscjames , @Blueskies00 has rightly pointed out a flaw in my logic on this test. (There are actually some cases where an OOC statement could be a component and have a true beneficialOwnerhsipOrControl interest.)

Huge apologies, but can we remove this test.

**Comment by odscjames** [comment]
It's gone
